name: Deploy to prod preview channel
"on": pull_request
jobs:
  build_and_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    env:
      GENERATE_SOURCEMAP: false
      REACT_APP_TIMERISE_API: "${{ secrets.PROD_REACT_APP_TIMERISE_API }}"
      REACT_APP_TIMERISE_WS: "${{ secrets.PROD_REACT_APP_TIMERISE_WS }}"
      REACT_APP_TIMERISE_TOOLS_API: "${{ secrets.PROD_REACT_APP_TIMERISE_TOOLS_API }}"
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TIMERISE_PROD }}"
          projectId: timerise-prod
