name: Deploy to development environment
on: [workflow_dispatch]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      GENERATE_SOURCEMAP: false
      REACT_APP_TIMERISE_API: "${{ secrets.DEV_REACT_APP_TIMERISE_API }}"
      REACT_APP_TIMERISE_WS: "${{ secrets.DEV_REACT_APP_TIMERISE_WS }}"
      REACT_APP_TIMERISE_TOOLS_API: "${{ secrets.DEV_REACT_APP_TIMERISE_TOOLS_API }}"
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TIMERISE_DEV }}"
          channelId: live
          projectId: timerise-dev
